### ISSUE TITLE
instance

### ISSUE THREAD

**Issue by LUK3D** [FaizanDurrani/UnityBackgroundAudio#1]
Hello! thanks for this awesome plugin. I just need to know if there is a way to make the instance variable public to access it in other methods.

**Comment by FaizanDurrani** [comment]
You can just declare the variable as `public BackgroundAudioImplementation ubaInstance;` and then get a new instance in Awake like so `ubaInstance = BackgroundAudioManager.NewInstance();`

**Comment by LUK3D** [comment]
Thak you!! You saved my live!!
