### ISSUE TITLE
Playing audio clip at X position

### ISSUE THREAD

**Issue by LUK3D** [FaizanDurrani/UnityBackgroundAudio#2]
How to start playing audio in a certain position?

I have an AudioSource that is already playing and I need UBA to start playing the audio in the exact position where my AudioSource Clip is

Please can you help me?

**Comment by FaizanDurrani** [comment]
You can use the Seek() method to seek to the desired position, it takes position in seconds as the parameter.

So to seek to 15 seconds you would do.
```cs 
Instance.Play();
Instance.Seek(15);
```

**Comment by FaizanDurrani** [comment]
Do keep in mind that the seek methods adds the seconds instead of moving to it.

For example if the audio playing is already at 15seconds then when you call the seek method it will go to 30seconds

**Comment by LUK3D** [comment]
Thank you very much


Em sáb., 16 de nov. de 2019 às 01:43, Faizan Durrani <
notifications@github.com> escreveu:
